version: "3.8"

services:
  local-dev-env:
    build:
      context: .
    volumes:
      - ..:/workspace:delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - vscode_extension:/root/.vscode-server/extensions
      - bashhistory:/commandhistory
    env_file:
      - .env
    command: tail -F anything
    network_mode: "host"
volumes:
  vscode_extension: null
  bashhistory: null